/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 12.05.2026 07:12:19

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1472;
#else
constexpr int kTensorArenaSize = 448;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,108 } };
const TfArray<1, float> quant0_scale = { 1, { 0.12318821251392365, } };
const TfArray<1, int> quant0_zero = { 1, { -88 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[2] = { -108, 108, };
const TfArray<1, int> tensor_dimension1 = { 1, { 2 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00015780213288962841, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[2*10] = { 
  59, -127, 69, 108, 117, -76, -42, -114, 45, 82, 
  77, 43, -22, -28, -91, 0, -112, 64, -126, 37, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 2,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0058445921167731285, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 16, 545, 0, -39, -61, 0, -111, 138, 649, -105, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0001518194330856204, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  32, -75, -66, 12, 109, 13, 127, -109, -6, -49, 7, 18, 63, 118, 52, -80, 3, -24, -67, 24, 
  -49, -111, 83, 65, 77, -23, -15, -97, -90, 38, -53, -51, 66, 57, 68, 87, -25, 33, -20, -16, 
  -22, -94, -3, 102, -47, -57, -35, 20, -40, -11, 31, 49, -21, -84, -13, -68, 82, -95, -97, -79, 
  61, 13, 97, 3, -77, 74, -67, -45, -27, 70, 111, 47, -72, -94, -5, -44, -26, -49, 100, 77, 
  -46, 58, -92, -42, -86, 66, -38, 24, -90, 57, 89, 56, -20, 46, 23, -92, -49, 99, 68, 54, 
  -85, 68, -68, 49, -30, -113, -7, 76, -113, -46, 75, 58, -49, 61, -23, -66, -36, 60, -66, 4, 
  91, 46, -63, -76, 62, 75, -3, -34, -26, -1, 74, 40, -68, -45, 8, -17, 53, -15, -20, -42, 
  -18, 88, 51, 60, 7, 84, 101, -106, 111, -26, -72, 110, 62, -19, -97, 49, 89, 2, 19, 91, 
  95, 40, 83, 40, 96, 54, -100, 12, -29, 33, 124, 21, -3, -89, -33, 93, -57, 69, -20, -11, 
  40, -70, -25, -2, 71, 96, -26, 8, 75, -93, -62, 47, -73, -56, 54, -18, -22, 88, 0, 70, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0039346790872514248, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -19, 0, 107, 0, 66, -14, 33, -40, 0, -26, 65, 0, -21, -10, -9, 0, 31, -18, -26, 6, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00030030854395590723, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*108] = { 
  4, 8, -46, 76, 34, 51, 37, -54, 29, -67, 3, 34, -75, -54, -39, 44, 18, 84, -18, -27, 91, -1, 89, 27, -75, 56, -60, -70, -62, -66, 30, 30, 64, -58, -73, 54, -50, 45, -47, -58, 40, -1, -58, -26, -79, 67, -32, 76, -52, -62, -50, -127, 20, 14, -37, 82, 108, 94, 107, 74, 44, -34, -21, -99, -19, -48, 14, 24, 81, 11, 33, -56, -50, 0, -50, -56, 44, 41, -6, 69, 23, -4, -23, 28, -8, 12, -114, -48, -72, -54, 62, 3, -25, 86, -2, -62, 96, 45, -89, -65, -10, -81, 26, 39, -17, -21, -21, 19, 
  -86, -6, 71, 11, -26, 15, 27, 26, 38, 81, -56, 36, 12, 16, 54, -47, 68, 43, 89, -52, -15, -9, 72, -17, 44, 42, -16, 63, -21, -64, -14, 82, 75, 85, 60, -28, -70, -8, 23, -40, -36, -48, 85, 61, 50, -23, 65, -61, 7, 0, -80, -10, 3, -33, -12, -89, -83, 70, 73, -70, -16, 60, -35, -15, -22, 1, 66, -87, 48, -23, 79, -50, 52, -5, 13, 72, -27, -50, -6, 78, -12, -88, -45, 0, 40, 7, -18, -64, 17, -21, 27, 27, 79, 20, 5, 49, -41, -72, 15, -77, 19, 83, -1, -12, -61, 41, 64, -56, 
  69, -25, -83, -50, 49, -59, 41, 60, 70, -21, -79, 1, -77, 29, -64, 53, 15, 39, -12, 23, 74, -95, 36, -82, -3, -36, 72, 30, -58, -82, -57, 45, 33, -76, -31, -42, -62, 7, 51, -55, 54, 33, -94, -28, 19, -30, -58, -83, 19, -36, 37, -14, -28, -13, 34, -85, -3, 0, -2, -36, 67, -43, -18, 6, -37, 38, 6, -62, -34, -42, -19, -99, 19, 62, -22, -63, -64, 35, -56, -66, 23, -60, 19, -16, -5, 2, -33, -10, -82, -12, -74, 59, 7, -43, 74, 47, 15, 30, 22, 13, -98, -89, -58, -75, 31, -47, 63, 50, 
  -73, 46, -46, 52, -7, 51, -9, 85, 43, -74, 71, 70, 42, 54, 38, -20, -67, -43, 29, 55, -57, 36, -57, -33, 53, 45, -63, 52, 73, 57, -39, 36, 73, -39, 53, 11, 86, -84, 17, 60, -72, 53, 1, 68, 84, -68, -4, -56, 52, 40, -57, -3, -17, -88, 21, -67, -75, -86, -36, -10, 79, 30, 83, 63, -58, -79, 50, -76, -55, -80, 50, -46, -47, -63, 19, 30, -22, 88, 31, 85, 17, 56, 61, -27, -17, -71, -8, -34, 53, -35, 35, 30, -72, 11, 72, -34, -52, -18, 69, -21, -28, -8, 70, -51, -42, -5, 11, -24, 
  79, 10, 8, -46, -58, -74, 66, -29, -50, 43, -34, 8, -63, -48, -69, 42, 43, 49, -16, -28, -19, 71, -26, -22, -35, -4, 54, 53, -88, -78, 32, -64, 68, -72, -36, -51, -20, -73, 21, 60, 19, 18, -84, -39, 41, -63, 57, 45, -25, 49, 51, 73, -76, -32, -33, 75, 46, 58, 69, 43, -83, -79, 74, 78, -2, 41, -45, 80, -98, -30, -83, 16, 68, 22, 29, 51, -17, -32, -51, -43, 57, -93, 37, -70, 21, -58, 12, -64, 51, -40, -42, -5, 12, 48, 18, -5, 9, -27, -73, -74, -26, -85, 13, -33, 69, -54, -91, -29, 
  -27, 68, 12, -5, -30, -67, 11, 89, -32, 21, -80, -30, -85, 43, 15, -7, -78, 28, -24, 10, -66, -69, -6, -42, 66, -21, 24, -14, -40, 89, -15, -8, 71, -51, 22, -79, 59, -54, 8, 75, 59, 35, -59, -22, 16, -85, -64, -57, -1, 58, 69, -41, 29, -31, 44, 56, 33, -7, 52, 9, 25, -82, 50, -78, -23, 2, -30, 70, 79, 43, 84, -37, 59, -61, -93, -59, -14, -12, 58, 2, -67, 34, -43, 71, -5, -66, 24, -19, 88, -12, 15, 9, -51, 70, 5, -5, -9, 30, -3, 50, -11, 29, 73, -50, 22, 17, 88, -56, 
  43, -38, -11, -47, -58, -93, -38, 59, -34, 3, -9, -11, -3, 47, 46, 10, -36, -58, 70, 57, -53, 2, -51, 48, -40, -12, 98, -57, 69, 13, 51, -86, -8, -22, -77, 40, -79, 48, -37, 91, -7, 13, -14, 1, -45, -75, 83, -50, -14, -22, -30, 112, -70, 33, 4, -28, -10, 54, 34, -46, -63, 6, 88, -25, 42, 14, -88, 56, -72, -64, 5, 66, -25, 26, 50, 60, 53, 66, 33, -40, 63, 52, 6, 22, -58, -29, 71, 54, -40, -55, -83, 39, -49, 71, -35, -98, -50, -55, -63, 12, -53, -57, -4, -24, 78, -26, -22, -70, 
  63, -72, 7, 72, 76, 33, 33, 41, -24, 79, -12, 90, -26, 39, -67, -104, -27, -36, -45, 94, 84, -43, -35, 7, -14, 89, -33, 12, -78, -5, 28, 87, 24, -68, -24, -71, -18, 12, 31, -33, -17, 32, 96, 89, 33, -7, 21, -71, -47, 47, -83, -52, -20, 30, -8, -39, -61, 76, 70, -74, -51, -25, 21, -85, 49, 32, 31, -33, -40, 100, -44, 27, -19, 50, -22, 9, -41, 53, -39, 45, 90, -84, 52, 1, 30, -79, 23, 14, 59, -17, -6, -61, 23, -40, -64, -26, -20, -71, -9, 66, -25, 59, 4, -75, -9, -21, -30, -67, 
  48, 84, 53, -15, -75, 54, -10, -52, -7, -14, 6, 54, 51, -32, 14, -38, 36, -41, 87, 18, 81, 60, 79, 36, 54, 56, 63, -8, 73, -77, 49, -83, -13, -1, -72, -25, -77, 74, -58, 8, -44, -45, -80, -34, -77, 26, -31, -11, -46, 26, -81, -86, 87, -55, 45, 42, 12, 41, -9, -33, 56, -20, 74, -35, 5, -84, 76, 63, 54, -45, -37, -27, 15, -71, -27, -79, -64, -40, -49, 74, -43, -51, -68, -40, 74, 19, -4, 31, 50, 48, 0, -80, -79, -20, 67, -6, 80, 21, 39, -49, -61, -53, -40, 39, 10, 63, -22, 10, 
  -75, 48, -89, -7, -50, 57, -74, 3, -46, -85, -71, -57, -85, -19, -62, 52, -8, 59, 72, -49, -11, 65, 24, 88, 92, 62, -1, 17, 0, 46, -34, -22, -58, 4, 67, 34, 58, 59, -41, 10, 18, 41, -43, 24, -36, -87, 59, 38, 79, -66, 25, 50, -88, -71, -37, 28, 60, 21, -72, 36, -73, -46, -81, 46, 2, -15, -77, -24, -56, 47, -49, 66, 75, 11, -33, -72, 74, -23, -83, 63, 46, 87, -75, -47, -58, 70, -71, -71, 43, 27, 82, 44, -16, -4, 15, 88, 3, -80, -78, -51, 56, -63, -71, -31, 16, 3, -82, -33, 
  97, 30, 6, -69, -46, -38, 51, 4, -15, 22, -73, 17, 14, -76, 14, -91, -16, 8, 49, 20, -71, 53, -77, 67, 65, -25, -63, -61, 48, 60, -91, -82, -65, -13, 85, 82, -12, -75, -114, 32, 40, -16, -1, -38, -40, 48, -7, -94, 47, 26, -67, -106, -39, 21, 105, 102, -42, -17, 29, -1, 21, 22, 23, 18, 6, -84, -82, 18, 47, 41, 68, 17, -7, -24, -39, 78, 14, -64, 34, 74, -47, -69, 7, -69, -39, 51, -61, -23, -51, -24, 29, 99, 50, -44, -18, 16, -49, 20, -102, 4, 57, 49, 36, 19, 45, -34, 4, -76, 
  -12, 30, 78, -27, -67, -79, 87, -35, 65, -20, 75, 81, 56, 80, -33, 40, -37, -31, 79, 2, -20, -19, 84, 3, 27, 35, 56, 43, 89, 34, -7, -19, 4, -36, 24, -20, -61, 22, 23, 47, 38, 63, 76, -14, -46, -27, 20, 41, -76, -8, -66, 59, 27, 30, 81, 51, 44, -16, 10, -71, 67, 47, -2, -24, 62, 53, 57, -22, -18, -20, -68, 3, -50, -53, 70, 24, 38, 71, 38, 15, 40, 80, -73, -47, -82, -79, -57, 41, -11, 57, 44, -69, -86, -66, 16, 26, 39, 58, -15, -24, -11, -6, 66, 62, 54, 34, 9, 86, 
  -44, -86, 7, -32, 50, -74, -51, -83, -69, 45, -18, -80, 22, 49, -26, 71, 14, -28, 74, -23, 43, 48, -56, 56, 46, -25, 11, -37, 78, -21, -37, 22, -81, 82, 56, 56, 68, -59, -66, -59, -16, 15, -69, -41, -86, -31, 84, 53, -13, 90, 65, -69, -83, 17, -58, -87, -59, 22, -19, 39, -27, -60, -59, 64, 17, 24, 57, 33, 14, 64, 2, -40, 37, 56, 33, -90, -39, 70, -73, -73, 16, 42, 78, 59, 83, 70, -75, -45, 6, 56, -62, 80, 20, 14, -61, -79, 33, 12, 62, -16, -60, 53, 41, 28, 3, -70, -4, 70, 
  14, -105, -18, -13, 65, 81, -82, 85, -9, 21, 16, 25, 79, 23, 4, -26, -80, -28, -90, -42, -79, -87, -16, -36, -39, -87, -42, 106, -9, 0, 22, -84, -73, -95, -16, 10, 32, 7, 116, -29, 78, 40, 68, -60, 79, -36, 1, 55, 85, 54, 66, 92, -46, -71, 46, -57, -7, 36, 28, -34, -7, -30, 18, -25, 67, 60, 64, 79, 13, 66, -79, -28, 48, -38, 77, -58, -33, -37, 40, -45, -31, 41, -14, -26, 42, 15, 92, 119, 5, -110, -22, 0, -76, 37, -87, -80, -47, 86, 25, -10, 23, 73, 17, -56, -57, 27, -8, -19, 
  79, -74, -47, 16, 5, -52, -39, 31, 42, 30, 86, -87, -75, 86, -86, -33, -77, 12, 50, -69, 75, 86, -44, 65, -82, -51, -12, -72, 70, -24, 89, -47, -39, 55, -13, -58, -71, 19, 71, -83, -89, 73, -84, 58, -13, 55, -32, -56, -85, -37, -17, 40, 29, -15, -66, -56, 80, -20, 77, -49, 6, 37, -52, 80, 13, 80, 76, 55, -15, 47, 10, -53, 78, -35, 77, 41, -38, 23, -2, 8, 47, 10, -59, -40, 17, -69, 67, 8, -72, 18, -39, 28, -13, 50, -74, -1, 69, 69, 72, 90, -81, 82, -57, 65, -72, -30, 55, -77, 
  0, 74, -66, -83, -82, 24, -11, 14, 32, 29, -5, 34, -49, 41, 41, 68, 15, 39, 31, 52, -81, 74, -72, 39, 20, 1, -39, -32, -17, -49, 23, -31, -32, 46, -7, 19, 0, -81, 22, 78, 51, -42, 26, -63, 62, -54, -79, -22, -64, 61, 37, -7, 62, 75, 35, -50, 77, 39, -64, 74, 2, -55, 16, -38, 14, 36, 14, -52, 8, 57, -76, 72, 71, 76, 36, 63, -37, 20, 74, 33, -62, -52, 12, 83, 88, 67, 8, 46, 50, 88, -3, 87, 18, 56, 84, 62, -73, 43, 47, 40, 67, 76, 84, -27, 60, -55, 13, 35, 
  2, -69, -18, -5, 69, -27, -37, -67, 29, -82, -82, -32, 17, 39, -21, 53, -71, -55, 25, -38, -84, -63, 24, -45, 32, -32, -7, 80, -64, 56, 25, -5, 61, -62, -34, -57, 27, -65, -9, 6, 1, -21, 9, 61, -12, -71, 66, -83, -11, -38, 31, 25, -12, -82, -33, -99, -27, -34, 46, -74, -64, 73, -29, 30, -62, 32, -6, -34, -7, 70, -81, -29, -45, 63, 87, 52, -31, 21, -58, 15, 16, 76, -88, -33, -13, 55, 18, -27, 83, -36, -7, 72, 70, 6, 8, -54, 0, -29, 91, -25, -14, -18, -22, -13, 73, 53, 33, 73, 
  -19, 45, 81, 60, 62, -25, -32, 76, 32, -9, -29, 88, -29, 64, -61, -27, -59, 25, 83, -47, 49, -35, -63, 89, -45, -66, -42, 31, -4, -49, -9, -65, 5, 24, 10, 89, 82, -49, 64, -76, -86, -24, 91, -24, 28, -56, 10, 86, -64, 45, -39, -49, 84, 49, 26, -64, 67, -75, -18, -40, 29, -67, 45, 85, -16, 49, -7, 4, 31, -23, 69, -31, 54, 82, 43, 19, -74, -63, 67, -66, -69, -78, -76, 17, 48, 84, -32, 22, 22, 41, 0, 87, -79, -43, 65, 48, 39, -29, 81, -78, 78, 38, 9, -51, -48, -87, -69, 85, 
  -76, -16, 39, -88, 42, 12, -53, -5, 1, -27, -78, -30, -72, -59, -68, -56, 8, -47, -41, 39, -38, 80, -43, 74, -35, -74, -5, -29, -76, -56, 45, -35, -51, -74, 91, 75, 22, -65, -92, -32, -66, 22, -49, 48, 5, -12, 91, 23, -67, -78, -10, -105, 39, -42, 66, -54, -50, -48, -18, 69, -24, -43, -73, 55, 45, -41, 81, -70, 9, 85, 60, 54, 64, -34, -94, 22, 73, 19, -22, 33, 28, 40, 78, 1, 47, 19, 70, -9, -3, -63, -76, 77, 62, -23, -60, -58, 53, 22, 78, -60, -86, 91, 25, 10, -41, 8, -40, -58, 
  -3, 63, 15, -42, -13, -31, 23, -13, 63, 60, -72, 69, 61, 0, 6, -24, -4, -80, -54, 21, -36, -83, 67, -72, -7, 3, -47, -32, 30, 66, -64, 11, 71, -56, 5, 26, -81, 22, 44, -10, -55, -63, 21, 48, 1, -70, -83, 23, -9, 5, 49, 81, -76, 20, 29, -51, 44, -75, -63, 68, -71, 61, -23, 42, -68, -14, -17, -63, -72, -55, -86, 53, -26, -15, 2, 32, -69, -87, -79, -39, 68, -6, -3, -77, -22, 32, 87, 9, 24, -7, -91, 9, -60, -18, 24, -78, -61, -61, 103, -47, -28, 66, 58, -70, -20, 53, -86, -66, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,108 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0024378024972975254, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.038584958761930466, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.026999682188034058, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,2 } };
const TfArray<1, float> quant9_scale = { 1, { 0.050822366029024124, } };
const TfArray<1, int> quant9_zero = { 1, { 31 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 108, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2160, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 112), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_980669_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_980669_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_980669_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_980669_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_980669_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
