/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_980669_4[] = { 0, 36, 72 };

// (before - mean) / scale
const float ei_classifier_anom_scale_980669_4[3] = { 0.013284934089081544, 0.02718562884032564, 0.015499195001508821 };
const float ei_classifier_anom_mean_980669_4[3] = { 0.15691805366230638, 0.3800246955238675, 0.2125323358433027 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_980669_4[8] = {
	{ ( float[3] ) { 0.9605079889297485, 1.33048677444458, 1.754652976989746 }, 2.0953808675924024 },
	{ ( float[3] ) { -1.2068573236465454, -1.128684401512146, -1.2887035608291626 }, 1.0995102307808688 },
	{ ( float[3] ) { 0.11974672228097916, 0.0857645645737648, 0.16365139186382294 }, 1.3205982555159808 },
	{ ( float[3] ) { -0.9909495115280151, -0.7851523160934448, -0.7349575757980347 }, 1.0854027496661458 },
	{ ( float[3] ) { -0.27232956886291504, -0.8624153733253479, -0.7722215056419373 }, 1.1098295613943192 },
	{ ( float[3] ) { 1.6827595233917236, 1.8175770044326782, 1.2526308298110962 }, 1.1057844756566815 },
	{ ( float[3] ) { 0.5321688055992126, 0.808214008808136, 0.7542343735694885 }, 1.2173101221643456 },
	{ ( float[3] ) { 1.4209645986557007, 0.892805278301239, 0.6863088011741638 }, 1.543836988058505 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
